### ISSUE TITLE
Where put my action data

### ISSUE THREAD

**Issue by cncolder** [danny-andrews/riot-redux#4]
First thanks to your good idea. I think this is the right way to make riot work with redux together.

Redux action is not only an action. Most time we need pass data to it. e.g. `this.loginUser('bob', '123')`. But in your code you bind all action as a event handler to prevent update. So I don't know where put my action data now.

**Comment by danny-andrews** [comment]
Thanks for the feedback! I added this ability in [0.0.3](https://github.com/danny-andrews/riot-redux/commit/8d1fb316c34f3ef4e469cf9e02b819db90a9d3a4). Let me know if it works for you!

**Comment by danny-andrews** [comment]
I'm so slow. I published a version below a git tag that already existed. Released in [0.2.0](https://github.com/danny-andrews/riot-redux/commit/9656cdbd1abbff14729ba8a23eb140ac76246f7b).
