### ISSUE TITLE
unsubscribe when unmount

### ISSUE THREAD

**Issue by watert** [danny-andrews/riot-redux#6]
the subscribe method already returns a unsubscribe method, why not unsubscribe it when the tag is unmounting?

``` javascript
let unsubscribe = subscribe.call(this, selector);
this.on("unmount", ()=> unsubscribe());
```

**Comment by danny-andrews** [comment]
Good catch. Released in [0.3.2](https://github.com/danny-andrews/riot-redux/commit/3bc73f67daca7705bb3499c2fb81eb67c46278f1).
