### ISSUE TITLE
More examples?

### ISSUE THREAD

**Issue by ckcollab** [danny-andrews/riot-redux#7]
Hey there! I am pretty new to Riot and very new to Redux, could you make an example that is a bit more complex, like some instances where `updates()` get confusing?

Will keep reading, thanks for all the work on this!

**Comment by danny-andrews** [comment]
You're welcome! Thanks for the feedback.
I think it might be helpful to read the docs on Riot and Redux to understand how updates work under the hood. The only thing this library does is provide a bridge between the two. The only time this library cals `update` on the riot component is when the value returned from `this.opts.selector` changes. We subscribe to the redux store to observe such changes.
